package pojos;
// Generated 7 feb. 2022 8:47:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipios generated by hbm2java
 */
public class Municipios  implements java.io.Serializable {


     private String idMunicipio;
     private String nombre;
     private Integer NHabitantes;
     private Set alumnoses = new HashSet(0);

    public Municipios() {
    }

	
    public Municipios(String idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Municipios(String idMunicipio, String nombre, Integer NHabitantes, Set alumnoses) {
       this.idMunicipio = idMunicipio;
       this.nombre = nombre;
       this.NHabitantes = NHabitantes;
       this.alumnoses = alumnoses;
    }
   
    public String getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(String idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getNHabitantes() {
        return this.NHabitantes;
    }
    
    public void setNHabitantes(Integer NHabitantes) {
        this.NHabitantes = NHabitantes;
    }
    public Set getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }

    @Override
    public String toString() {
        return "Municipios{" + "idMunicipio=" + idMunicipio + ", nombre=" + nombre + ", NHabitantes=" + NHabitantes + ", alumnoses=" + alumnoses + '}';
    }




}


